### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by mrprompt** [PHPSC/phpsc.github.io#1]
É preciso adicionar um layout para o projeto, para melhorar a navegação e etc.

**Comment by sergiors** [comment]
Estou fazendo isso =D até semana q vem mando algo pra aprovar =D

**Comment by sergiors** [comment]
Quais as sugestões até o momento?

**Comment by mrprompt** [comment]
Por enquanto: nenhuma :P

**Comment by mrprompt** [comment]
Acho que seria legal, colocarmos uns ícones com os links do site (facebook, twitter, linkedin e etc), assim como um espaço para publicidade dos apoiadores oficiais, o que acham?

**Comment by rafaelscbr** [comment]
@sergiors posso te ajudar? em sugestões?

**Comment by sergiors** [comment]
@rafaelscbr estou implementando o bootstrap, algo que dá pra já adiantar é colocar o bs com sass pro jekyll compilar..

**Comment by whera** [comment]
Em plataformas mobile não está aparecendo o menu

**Comment by mrprompt** [comment]
vamos criar uma issue entao

**Comment by mrprompt** [comment]
ping
