### ISSUE TITLE
Configurar para utilizar as variáveis do Bootstrap nos arquivos Sass

### ISSUE THREAD

**Issue by sergiors** [PHPSC/phpsc.github.io#30]
Essa task ajudará e utitlizar as vars no bootstrap, podendo configurar a cor do navmenu, dropdowns, etc.. sem sobrescrever as regras CSS..

Além de ter mixins para escrever as media-queries.

**Comment by mrprompt** [comment]
ping @sergiors

**Comment by sergiors** [comment]
Por hora é melhor sobrescrever mesmo o bootstrap.. já que temos um volume baixo de contribuição, essa organização é muito overhead
