### ISSUE TITLE
Explicação do formato dos meetups

### ISSUE THREAD

**Issue by sergiors** [PHPSC/phpsc.github.io#32]
Cria uma página para mostrar o formato do PHPSCInCompany e PHPSCInPub e um lugar com o histórico dos talks antigos, como o http://floripajs.org

**Comment by mrprompt** [comment]
show! :+1:

**Comment by sergiors** [comment]
Essa feature ta no forno!

**Comment by mrprompt** [comment]
:+1:

**Comment by mrprompt** [comment]
@sergiors o que tu acha de utilizarmos algo como esse formato, na pasta _data:

```
1st_incompany:
  data:
  local:
  publico:
  temas:
    -

1st_phpub:
  data:
  local:
  publico:
  temas:
    -
```

Assim não precisamos escrever nenhum plugin, tão pouco conversar diretamente com a API do Meetup.

**Comment by mrprompt** [comment]
@mingomax da uma olhada também por favor e me diz o que tu pensa disso.

**Comment by sergiors** [comment]
Eu nao vejo necessidade de catalogar os pubs, apenas apresentar a ideia e linkar os posts relacionados dos pub ocorridos e mostrar a data do proximo pub..

Já os incompany como temos talks definidas certinho, vale a pena manter o histórico com links dos slides e tal..

**Comment by mrprompt** [comment]
Não discordo, mas acho legal os dois, pra galera saber realmente da existência e do que rolou. Já que nos pubs rolam conversas bem interessantes também.

**Comment by sergiors** [comment]
:+1: o pub como é mais solto, teria q sempre rolar um overview e deixar registrado..

Outra, temos já q pensar em uma descrição do formado de cada um, tipo:

Pub: A ideia do pub é juntar a galera em um bar para conversar sobre desenvolvimento em geral, trocar figurinha

InCompany: O inCompany tem foco em levar a comunidade para dentro das empresas, para conhecer o ecossistema corporativo..

**Comment by mrprompt** [comment]
Beleza, acho ótimo.

**Comment by mingomax** [comment]
Eu gosto do formato do FloripaJS, mas nao gosto dessa coisa "Próximo encontro" com a data do ultimo. Fica bizarro quando tu entra e tem la Proximo encontro dia 19 de Dez.

O que quero dizer, a ideia do @mrprompt  de colocar o histórico super válida e cara colocar duas palavrinhas ali de como foi o Pub  nao custa nada, ja fazemos isso. É mais para ter um local dentro do site centralizando isso.

o InCompany também segue o mesmo principio. E galera precisamos nos apropriar disso a aprender a deixar registrado as paradas que fazemos enquanto comunidade. 

Mas assim vamos fazer o simples mas organizado e q tenha propósito.

**Comment by sergiors** [comment]
:+1: vou fazer um skeleton, dai coloco aqui pra gente evoluir..

**Comment by sergiors** [comment]
como o @mrprompt citou sobre os proximo encontro... O que acham de ter no topo o proximo encontro e abaixo uma lista dos encontros ocorridos?

**Comment by mingomax** [comment]
@sergiors Massa! Curti a idéia. Fica com cara de historico mesmo.!

**Comment by mrprompt** [comment]
Eu acho legal deixar como destaque o próximo encontro, mas como o @mingomax falou, é bizarro ver algo que já passou como destaque, então, temos que nos organizar para deixar a página sempre atualizada.

**Comment by mrprompt** [comment]
@sergiors eu já comecei o yml aqui com os dados, to quase acabando

**Comment by mrprompt** [comment]
@sergiors @mingomax inseri um _data/meetups.yml com uma estrutura simples de todos os meetups que ocorreram, podemos trabalhar a página juntos.

Para exibir o próximo evento, é só pegar o último da lista - os mais antigos estão no topo - e verificar se a data do registro confere como futuro ou passado.

**Comment by sergiors** [comment]
fechou, vou me programar pra essa semana apresentar algo já

**Comment by mrprompt** [comment]
A página já está no ar, no link /reunioes/ e está ordenada do meetup mais atual para o mais antigo, por enquanto, sem tratamento algum para mostrar se é futuro ou passado, precisa também dar um belo tapa no layout.

**Comment by mingomax** [comment]
@mrprompt troca par 4th ao invés de 4rd cade os revisores? Ta indo bug para produção hauahuahuahau

Outra coisa para o Próximo não tem como dar um destaque?

**Comment by mrprompt** [comment]
@mingomax  ahahahaha foi mal troco sim.

Sobre tratar o próximo dá sim, só preciso trocar o formato da data no yml para poder comparar.

**Comment by mrprompt** [comment]
acoh que esta questão também já está fechada né ?
