### ISSUE TITLE
Dar visibilidade aos projetos do grupo

### ISSUE THREAD

**Issue by mrprompt** [PHPSC/phpsc.github.io#48]

**Comment by whera** [comment]
@mrprompt tais pensando em fazer como?

**Comment by mrprompt** [comment]
Estava pensando em uma página simples, listandos os projetos principais do grupo, com uma descrição - pode ser a mesma do README de cada um.
- [ ]  phpsc-conf
- [ ]  pagseguro
- [ ]  empresas
- [ ]  meetups

**Comment by jzonta** [comment]
Pode ser mais um link no menu principal? "Projetos"
Dentro o nome, descrição e link para o github.
Sinaliza ai se for isso, aproveito o feriado para fazer essa implementação.

**Comment by whera** [comment]
@jzonta Acredito que sim...
existe uma pagina semelhante no menu [reuniões](https://www.phpsc.com.br/reunioes/)
