### ISSUE TITLE
Slack - Link quebrado

### ISSUE THREAD

**Issue by whera** [PHPSC/phpsc.github.io#49]

**Comment by mrprompt** [comment]
Apenas para deixar claro, o link quebrado é o do [Slack-In](https://phpsc-slackin.herokuapp.com), ainda é possível entrar com o [link direto do Slack](https://php-sc.slack.com).

**Comment by sergiors** [comment]
Parece que o slack-in ta funcionando.

**Comment by mrprompt** [comment]
está, por isso fechei o card
